name = input("enter your full name:")
sudent_id =input ("enter your full student ID:")
department = input ("enter your department :")
github_username = input ( "enter your github username :")
programming_goal = input("enter one programming goal:")

print("/n " + "="* 40)
print("    STUDENT PROFİLE CARD    ")
print("=" * 40)
print(f" name:     {name} ")
print(f" student ID :    {student_id}  ")
print(f" department :    {department}")
print(f" github username :   {github_username}")
print(f" goal:   {programming_goal}")
print("="*40)
